spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/datatest
    username: postgres
    password: harianbu@3
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      minimum-idle: 5

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    baseline-description: "Base schema initialization"
    user: postgres
    password: harianbu@3

  jpa:
    hibernate:
      ddl-auto: validate  # validate checks if schema matches, set to 'update' for automatic updates
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
